spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=300MB
spring.servlet.multipart.enabled=true
server.port=${PORT:8080}

# evita arquivos temporários gigantes
spring.servlet.multipart.file-size-threshold=2MB

# PROFILE ATIVO
spring.profiles.active=dev

# JWT BASE (usado em todos ambientes)
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

logging.level.org.springframework.security=TRACE

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.jdbc=DEBUG