spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Sobrescreve o secret em produção
jwt.secret=${JWT_SECRET}

# ==========================================================
# DESATIVA OPEN-IN-VIEW
# Evita consultas ao banco fora da camada de serviço
# Melhora controle de transação e performance
# ==========================================================
spring.jpa.open-in-view=false
